export const TYPES = {
  FETCH_ALL_NOTES: 'FETCH_ALL_NOTES',
  GET_SPECIFY_NOTE: 'GET_SPECIFY_NOTE',
  ADD_NEW_NOTE: 'ADD_NEW_NOTE',
  CHANGE_NEW_TITLE: 'CHANGE_NEW_TITLE',
  REMOVE_NOTE: 'REMOVE_NOTE',
  SET_BACKGROUND_COLOR: 'SET_BACKGROUND_COLOR',

  SET_NEW_TAG: 'SET_NEW_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  SET_NEW_TAG_NAME: 'SET_NEW_TAG_NAME',

  ADD_COMMENT: 'ADD_COMMENT',
  ADD_DESCRIPTION: 'ADD_DESCRIPTION'
};